name: Release Libs

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create libs.zip
        run: |
          zip -r libs.zip llstd llgui llweb
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: libs.zip
          token: ${{ secrets.PAT_TOKEN }}
