name: Release Libs

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create libs.zip
        run: |
          zip -r libs.zip llstd
      
      - name: Upload Release Asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: "libs.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          makeLatest: true
